version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - install_dependencies:
          name: Install Dependencies
          command: go get ./...
      - build:
          name: Build application
          command: go build -o app cmd/server/main.go
      - run:
          name: Run application
          command: docker-compose up --build -d
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - integration_tests:
          name: Run integration tests
          command: go test -tags=integration -v ./...
      - acceptance_tests:
          name: Run acceptance tests
          command: go test -tags=e2e -v ./...

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - build